#!/bin/sh

if [ $# -ne 0 ]; then
  exec $@
fi

set -e

# The container runs as the invoking user, who has no home directory here.
export HOME=/tmp
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_NOLOGO=1

# Build JS
#
# The tooling comes from package-lock.json rather than from the image so that
# the generated documentation depends only on what the repository records.
cd /srv/js
npm ci
npx jest
rm -rf docs
npx jsdoc -d docs -c jsdoc.conf gmn.js

# Build Java
cd /srv/java
javac -encoding UTF-8 org/gs1/GMN.java
javac -encoding UTF-8 -cp .:/usr/share/java/junit4.jar GMNTests.java
java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore GMNTests
jar -cvf GMN.jar org/gs1/*.class
rm -rf docs
javadoc -d docs -notimestamp org.gs1
sed -i '/^.*!-- Generated by javadoc.*$/d' docs/index.html

# Build C#
cd /srv/cs
dotnet build GMN/GMN.csproj
dotnet test GMNTests/GMNTests.csproj
dotnet pack -c Release -o app GMN/GMN.csproj
cp app/GMN.*.nupkg .

# Build C# docs
rm -rf docs
(cd docfx_project && docfx docfx.json)
rm -f docs/manifest.json  # Build artefact that records absolute paths
ln -s GS1.html docs/index.html
