name: .NET Core (Linux)

on:
  push:
    branches: [master]
    paths:
      - "cs/**"
      - ".github/**"
  pull_request:
    branches: [master]
    paths:
      - "cs/**"
      - ".github/**"

defaults:
  run:
    working-directory: cs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.101

      - name: Install dependencies
        run: |
          dotnet restore GS1GMN.sln

      - name: Build
        run: |
          dotnet build GMN/GMN.csproj --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test GMNTests/GMNTests.csproj --no-restore --verbosity normal

      - uses: nikeee/docfx-action@master
        name: Generate docfx documentation
        with:
          args: cs/docfx_project/docfx.json

