name: .NET Core (Windows)

on:
  push:
    branches: [master]
    paths:
      - "cs/**"
  pull_request:
    branches: [master]
    paths:
      - "cs/**"

defaults:
  run:
    working-directory: cs

jobs:
  ci-mswin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: MSVC CI
        run: dotnet build

      - name: Install dependencies
        run: dotnet restore GS1GMN.sln
      - name: Build
        run: dotnet build GMN/GMN.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test GMNTests/GMNTests.csproj --no-restore --verbosity normal
